spring:
  application:
    name: my-market-app

  liquibase:
    change-log: classpath:/db/changelog/scripts/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/my-market-app
    username: my_market_user
    password: my_market_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false